.github/workflows/katacoda.yml, .github/workflows/linter.yml, .github/workflows/s3publish_pr.yml, .github/workflows/s3publish_pr_close.yml, .github/workflows/test-links.yml, docs/new.md
add new linter feature in release note
=> add linter feature

docs/new.md
=> pr preview feature

.github/workflows/linter.yml, .github/workflows/s3publish_pr.yml, .github/workflows/s3publish_stable.yml, docs/new.md
=> preview comment

common/.github/actions/pr-preview-publish/action.yml, common/.github/actions/release-publish/action.yml
=> remove debug

.github/pull_request_template.md
Updating PR template with new URL
and testing CodeOwner at the same time
=> Updating PR template with new URL

docs/create/advanced/add-css-and-js.md, mkdocs.extra.yml, mkdocs.navigation.yml
Add config for extra CSS and scripts as a comment template in `mkdocs.extra.yml`
Documents ConsenSys/doctools.action-builder#6
=> add css and scripts config example

.github/pull_request_template.md, docs/contribute/index.md, docs/contribute/markdown/extensions.md, docs/overview/new-features.md
Upload demo video and embed YouTube link. Minor fix to PR template.
fixes #23
=> upload demo video

docs/contribute/style-guide.md, docs/overview/index.md, docs/reference/release-process.md
Add reference to the Divio documentation system guide.
Also, change instances of "master" to "main."
fixes #27 
=> add doc system guide link & master -> main

docs/overview/index.md
Move QBS to new doc system list.
fixes #29 
=> Move QBS to new doc system list

mkdocs.yml
add config files to be watched for changes that will trigger refresh of the doc when modified. No need for reloading the container when modifying config files other than the main mkdocs.yml file.
Note that this has to be in each site config and not in the base.yml common config because at the build image level we can';t assume the names of the files that are in the final site. It could lead to errors. Also it allows each site to add or remove files in this watch list.
split config files were not firing refresh of the local doc preview when modified.
For instance when modifying the mkdocs.navigation.yml file, you had to re-run docker compose up. …
=> add config files to be watched for changes

.github/workflows/linkcheck.yml, .github/workflows/lint.yml, .github/workflows/pr_preview_delete.yml, mkdocs.watch.yml
- remove no sec env, useless
- fix workflow triggers
- move watch config in file
needed cleanup:
- Useless env
- useless pull trigger
- watch config not in the right place
=> CI and preview changes

docs/contribute/index.md
Add resouce for Git beginners.
fixes #41 
=> add git resource

docs/contribute/style-guide.md
Add guide on documentation categories
fixes #43 
=> add doc categories guide

docs/examples/home_with_content.md
Add ConsenSys NFT home page example using the `home_with_button.html` template. This template is edited for font size and margin in https://github.com/ConsenSys/doctools.action-builder/pull/19.
=> Add home with content example

.github/workflows/case.yml, .github/workflows/latest_publish.yml, .github/workflows/linkcheck.yml, .github/workflows/lint.yml, .github/workflows/pr_preview_delete.yml, .github/workflows/pr_preview_publish.yml, .github/workflows/release_publish.yml, .github/workflows/spelling.yml, CODEOWNERS
- add case check
- update CODEOWNERS (docOps team was renamed)
- update checkout action version
Just an update to port changes made on CI for QBS doc.
=> Add case check

docs/contribute/markdown/configure-and-format.md
Add info on naming files to the MD guide.
fixes #46 
=> Add file naming guidance

docs/contribute/style-guide.md
Fix left padding on list item in the style guide.
=> [MINOR] Fix left padding on style guide

docs/contribute/style-guide.md
Fix padding on style guide list item.
=> [MINOR] Fix padding on list item

.github/vale/styles/Vocab/Consensys/accept.txt, .github/workflows/case.yml, .github/workflows/latest_publish.yml, .github/workflows/linkcheck.yml, .github/workflows/lint.yml, .github/workflows/pr_preview_delete.yml, .github/workflows/pr_preview_publish.yml, .github/workflows/release_publish.yml, .github/workflows/spelling.yml, docs/index.md, mkdocs.watch.yml
- Add CI jobs sync
- add watch on main config
- add acronyms plurals to spellchecker
- 
replaces #51 that was on a fork
=> Misc updates

docs/contribute/index.md, docs/contribute/markdown/extensions.md, docs/examples/support.md, docs/overview/index.md, docs/preview/old-system.md, mkdocs.extra.yml
Updated discord link to https://discord.com/invite/consensys
Discord invite was not using the unified one
=> update discord link according to INFSC-228
